### ISSUE TITLE
您好，Release  中的 onnx模型链接一直刷不出来，您能否放百度网盘上让我们自行下载呢？谢谢了

### ISSUE THREAD

**Issue by XuHao9166** [Crescent-Ao/GGHL-Deployment#4]

**Comment by Crescent-Ao** [comment]
不好意思，好像确实忘记了放入ONNX，您可以去https://github.com/Shank2358/GGHL，下载pth文件。https://github.com/Crescent-Ao/GGHL-Deployment/blob/main/TensorRT/python/torch2onnx.py，这里有转换的工具。
